//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisfactoryModdingHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SatisfactoryModdingHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Transformers.
        /// </summary>
        public static string AccessTransformersPageTitle {
            get {
                return ResourceManager.GetString("AccessTransformersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 650.
        /// </summary>
        public static string App_Settings_Height {
            get {
                return ResourceManager.GetString("App_Settings_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string App_Settings_Width {
            get {
                return ResourceManager.GetString("App_Settings_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SatisfactoryModdingHelper.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Async Library.
        /// </summary>
        public static string CPP_Buttons_GenerateAsync {
            get {
                return ResourceManager.GetString("CPP_Buttons_GenerateAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Default C++ Files.
        /// </summary>
        public static string CPP_Buttons_GenerateDefault {
            get {
                return ResourceManager.GetString("CPP_Buttons_GenerateDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ Tools.
        /// </summary>
        public static string CPP_Title {
            get {
                return ResourceManager.GetString("CPP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPP.
        /// </summary>
        public static string CPPPageTitle {
            get {
                return ResourceManager.GetString("CPPPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Contain Content.
        /// </summary>
        public static string JSON_CanContainContent {
            get {
                return ResourceManager.GetString("JSON_CanContainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string JSON_Category {
            get {
                return ResourceManager.GetString("JSON_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string JSON_CreatedBy {
            get {
                return ResourceManager.GetString("JSON_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By URL.
        /// </summary>
        public static string JSON_CreatedByURL {
            get {
                return ResourceManager.GetString("JSON_CreatedByURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string JSON_Description {
            get {
                return ResourceManager.GetString("JSON_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs URL.
        /// </summary>
        public static string JSON_DocsURL {
            get {
                return ResourceManager.GetString("JSON_DocsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Version.
        /// </summary>
        public static string JSON_FileVersion {
            get {
                return ResourceManager.GetString("JSON_FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly Name.
        /// </summary>
        public static string JSON_FriendlyName {
            get {
                return ResourceManager.GetString("JSON_FriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string JSON_Installed {
            get {
                return ResourceManager.GetString("JSON_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Beta Version.
        /// </summary>
        public static string JSON_IsBetaVersion {
            get {
                return ResourceManager.GetString("JSON_IsBetaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Experimental Version.
        /// </summary>
        public static string JSON_IsExperimentalVersion {
            get {
                return ResourceManager.GetString("JSON_IsExperimentalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace URL.
        /// </summary>
        public static string JSON_MarketplaceURL {
            get {
                return ResourceManager.GetString("JSON_MarketplaceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string JSON_Plugins {
            get {
                return ResourceManager.GetString("JSON_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string JSON_Plugins_Enabled {
            get {
                return ResourceManager.GetString("JSON_Plugins_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string JSON_Plugins_Name {
            get {
                return ResourceManager.GetString("JSON_Plugins_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem Version.
        /// </summary>
        public static string JSON_Plugins_SemVersion {
            get {
                return ResourceManager.GetString("JSON_Plugins_SemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem Version.
        /// </summary>
        public static string JSON_SemVersion {
            get {
                return ResourceManager.GetString("JSON_SemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support URL.
        /// </summary>
        public static string JSON_SupportURL {
            get {
                return ResourceManager.GetString("JSON_SupportURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPlugin Editor.
        /// </summary>
        public static string JSON_Title {
            get {
                return ResourceManager.GetString("JSON_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string JSON_Version {
            get {
                return ResourceManager.GetString("JSON_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Name.
        /// </summary>
        public static string JSON_VersionName {
            get {
                return ResourceManager.GetString("JSON_VersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All In One.
        /// </summary>
        public static string Main_Button_AIO {
            get {
                return ResourceManager.GetString("Main_Button_AIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpakit.
        /// </summary>
        public static string Main_Button_Alpakit {
            get {
                return ResourceManager.GetString("Main_Button_Alpakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpakit &amp; Launch.
        /// </summary>
        public static string Main_Button_Alpakit_Launch {
            get {
                return ResourceManager.GetString("Main_Button_Alpakit_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Base C++ Files.
        /// </summary>
        public static string Main_Button_CPP {
            get {
                return ResourceManager.GetString("Main_Button_CPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Development Editor.
        /// </summary>
        public static string Main_Button_DevEditor {
            get {
                return ResourceManager.GetString("Main_Button_DevEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Satisfactory.
        /// </summary>
        public static string Main_Button_Launch {
            get {
                return ResourceManager.GetString("Main_Button_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch SMM.
        /// </summary>
        public static string Main_Button_Launch_SMM {
            get {
                return ResourceManager.GetString("Main_Button_Launch_SMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Shipping.
        /// </summary>
        public static string Main_Button_Shipping {
            get {
                return ResourceManager.GetString("Main_Button_Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate VS Files.
        /// </summary>
        public static string Main_Button_VS {
            get {
                return ResourceManager.GetString("Main_Button_VS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Plugin.
        /// </summary>
        public static string ModPlugin {
            get {
                return ResourceManager.GetString("ModPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Satisfactory Before Packing.
        /// </summary>
        public static string Settings_Alpakit_CloseGame {
            get {
                return ResourceManager.GetString("Settings_Alpakit_CloseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Settings_Alpakit_CloseGame_Value {
            get {
                return ResourceManager.GetString("Settings_Alpakit_CloseGame_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Mod to Folder.
        /// </summary>
        public static string Settings_Alpakit_CopyMod {
            get {
                return ResourceManager.GetString("Settings_Alpakit_CopyMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Settings_Alpakit_CopyMod_Value {
            get {
                return ResourceManager.GetString("Settings_Alpakit_CopyMod_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGS.
        /// </summary>
        public static string Settings_Alpakit_EGS {
            get {
                return ResourceManager.GetString("Settings_Alpakit_EGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGS Experimental.
        /// </summary>
        public static string Settings_Alpakit_EGS_Exp {
            get {
                return ResourceManager.GetString("Settings_Alpakit_EGS_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Settings_Alpakit_Launcher_Value {
            get {
                return ResourceManager.GetString("Settings_Alpakit_Launcher_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        public static string Settings_Alpakit_Steam {
            get {
                return ResourceManager.GetString("Settings_Alpakit_Steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpakit Settings.
        /// </summary>
        public static string Settings_Alpakit_Text {
            get {
                return ResourceManager.GetString("Settings_Alpakit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Settings_Button_Browse {
            get {
                return ResourceManager.GetString("Settings_Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreal Project Folder.
        /// </summary>
        public static string Settings_Locations_Project {
            get {
                return ResourceManager.GetString("Settings_Locations_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\code\SML-master.
        /// </summary>
        public static string Settings_Locations_Project_Hint {
            get {
                return ResourceManager.GetString("Settings_Locations_Project_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfactory Game Folder.
        /// </summary>
        public static string Settings_Locations_Satisfactory {
            get {
                return ResourceManager.GetString("Settings_Locations_Satisfactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Steam\steamapps\common\Satisfactory.
        /// </summary>
        public static string Settings_Locations_Satisfactory_Hint {
            get {
                return ResourceManager.GetString("Settings_Locations_Satisfactory_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMM Folder.
        /// </summary>
        public static string Settings_Locations_SMM {
            get {
                return ResourceManager.GetString("Settings_Locations_SMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %LOCALAPPDATA%\Programs\Satisfactory Mod Manager.
        /// </summary>
        public static string Settings_Locations_SMM_Hint {
            get {
                return ResourceManager.GetString("Settings_Locations_SMM_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commonly Used Locations.
        /// </summary>
        public static string Settings_Locations_Text {
            get {
                return ResourceManager.GetString("Settings_Locations_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS Unreal Engine Folder.
        /// </summary>
        public static string Settings_Locations_UE {
            get {
                return ResourceManager.GetString("Settings_Locations_UE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Unreal Engine - CSS.
        /// </summary>
        public static string Settings_Locations_UE_Hint {
            get {
                return ResourceManager.GetString("Settings_Locations_UE_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio Folder.
        /// </summary>
        public static string Settings_Locations_VS {
            get {
                return ResourceManager.GetString("Settings_Locations_VS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE.
        /// </summary>
        public static string Settings_Locations_VS_Hint {
            get {
                return ResourceManager.GetString("Settings_Locations_VS_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessTransformers.
        /// </summary>
        public static string ShellAccessTransformersPage {
            get {
                return ResourceManager.GetString("ShellAccessTransformersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPP.
        /// </summary>
        public static string ShellCPPPage {
            get {
                return ResourceManager.GetString("ShellCPPPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPlugin.
        /// </summary>
        public static string ShellUPluginPage {
            get {
                return ResourceManager.GetString("ShellUPluginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPlugin.
        /// </summary>
        public static string UPluginPageTitle {
            get {
                return ResourceManager.GetString("UPluginPageTitle", resourceCulture);
            }
        }
    }
}
